# Generated by Django 4.0.2 on 2022-02-21 15:48

from django.conf import settings
from django.db import migrations, models
import quote.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=quote.models.on_delete_user, to=settings.AUTH_USER_MODEL),
        ),
    ]
