# Generated by Django 4.0.2 on 2022-02-21 17:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quote', '0005_alter_rate_score'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'quote')},
        ),
    ]
